Feature/apartment registration verification filtering
intr00der/apartments-service pull request #8
Opened 2021-05-24 17:06 UTC by intr00der

2021-05-28 08:45 UTC, HackoDev requested changes

2021-05-28 08:45 UTC, HackoDev commented on .gitignore
> +src/media
?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +        owner_id = self.user.pk
не понимаю, зачем такой жирный метод? Почему нельзя через form.save() это победить?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +        room_amount = self.cleaned_data.get('room_amount')
почему `.get`?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +        room_amount = self.cleaned_data.get('room_amount')
почему везде get

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +        if closes_at < opens_at:
разве есть такой кейс, что полей не будет?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +            raise forms.ValidationError(
```python
raise forms.ValidationError({
    'closes_at': "It's not possible to set the closing date earlier than the opening date.",
})
```

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    amount_choices = Apartment.Amount.choices
плохо как-то, завязка на индексы ужасная. Лучше перечисли, чем так.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    amount_choices = Apartment.Amount.choices
именуем choice верхним регистром, а то как-будто обычные переменные/поля

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    search_bar = forms.CharField(required=False, label='Search by country, city, description')
почему все поля не обязательные?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    def filter_apartments_by_query(self, request):
форма отвечает только за валидацию, но не за бизнес-логику филтрации.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +                    {'bedroom_amount': ["It's not possible to have more bedrooms than rooms overall."]})
оформление кода аналогично, как я выше написал

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    def clean(self, *args, **kwargs):
что есть args, kwargs? validate принимает только словарь и всё.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +                {'starts_at': ['Some or all dates the from chosen date interval are already booked']})
не нужно список в ошибки писать, одна ошибка просто строкой

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +        crossed_bookings = Booking.objects.filter(
код читается тяжело.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +            raise forms.ValidationError({'ends_at': ["Starting date can't be later than ending date."]})
не нужен список (везде)

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    def create_review_by_form(self):
есть метод save, зачем писать свое?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/models.py
> +        if self.is_verified:
почему так? объявления не могу быть опубликованы, пока пользователя ее заверифицировали. он может создать черновик, но верификация идет отдельно. Сайд эффекты - это плохо.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/models.py
> +    class Rating(models.IntegerChoices):
давай лучше Min/Max валидаторами, вообще не нравится choice.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/models.py
> +        apartment_ratings = Review.objects.filter(apartment=self.apartment).values('rating')
вынесем эту логику за пределы модели.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/models.py
> +        apartment_ratings = Review.objects.filter(apartment=self.apartment).values('rating')
это уже похоже на сервис, а не на логику модели: опять же это похоже на сайд эффект

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/models.py
> +        apartment_ratings = Review.objects.filter(apartment=self.apartment).values('rating')
и почему нельзя использовать Avg на уровне ORM/SQL?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/services.py
> +    apartment = Apartment.objects.get(id=apartment_pk)
ты берешь объект из базы со всеми его полями только лишь с целью обновить 1 поле.
Если тебе не нужен объект, то не бери его из базы вообще. просто обнови и всё.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/services.py
> +    default_timedelta = timedelta(days=60).days
что такое 60?)) вынеси в константу

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/services.py
> +    date_lst = date_str.split('.')
плохо решение, используй `datetime` модуль.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/services.py
> +        booked_days += [start + timedelta(days=x) for x in range(0, (end - start).days)]
используй метод добавления элементов в список вместо +=

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/services.py
> +def get_formatted_date_list(date_list):
это не нужно, вынеси просто на уровень сериалайзера и он всё сделает.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +            redirect('home')
?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +    return HttpResponse(status=500)
почему 500?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +                    redirect('apartment-detail', {'form': form})
?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +                    redirect('apartment-detail', {'form': form})
вижу, что ты не тестировал какие-то части кода.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +        apartment = Apartment.objects.get(pk=apartment_pk)
уже писал- всё в try это зашквар.

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +        if request.method == 'GET':
всё в try это ...

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +    return HttpResponse(status=500)
зачем тебе вообще эти проверки на типы методов?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +    return HttpResponse(status=500)
и почему 500?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +        apartment = Apartment.objects.get(pk=apartment_pk)
...

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +    bookings = Booking.objects.filter(user=user)
используй пагинатор, вдруг чувак каждый день путешествует и у него сотни броней (отмененные / ждущие / старые)

2021-05-28 08:45 UTC, HackoDev commented on src/apps/apartments/views.py
> +        user = request.user
...

2021-05-28 08:45 UTC, HackoDev commented on src/apps/users/admin.py
> +class UserAdmin(admin.ModelAdmin):
переиспользуй логику django.auth- как же создавать пользователей теперь из админки?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/users/forms.py
>          except ValidationError as err:
зачем tryx/except

2021-05-28 08:45 UTC, HackoDev commented on src/apps/users/managers.py
> +            born_in=born_in,
просто `birthday`

2021-05-28 08:45 UTC, HackoDev commented on src/apps/users/managers.py
> +            country=Country.objects.get(pk=country),
зачем брать из базы, не понимаю

2021-05-28 08:45 UTC, HackoDev commented on src/apps/users/services.py
> +    return int((date.today() - user.born_in).days/365)
форматирование кода

2021-05-28 08:45 UTC, HackoDev commented on src/apps/users/views.py
> +            redirect('profile')
?

2021-05-28 08:45 UTC, HackoDev commented on src/apps/users/views.py
> +            if request.user.pk != int(user_pk):
....

2021-05-28 08:45 UTC, HackoDev commented on src/conf/settings.py
> -STATIC_ROOT = os.path.join(BASE_DIR, 'static')
куда дел static_root?

2021-05-28 08:45 UTC, HackoDev commented on src/conf/urls.py
> +urlpatterns += static(
в продакшене такого не надо, только для разработки

2021-05-28 09:41 UTC, intr00der commented on src/apps/apartments/forms.py
> +    search_bar = forms.CharField(required=False, label='Search by country, city, description')
Я предполагаю, что человеку не обязательно заполнять все поля, чтобы отфильтровать, ведь нам зачастую в интернет-магазинах надо всего одно слово в поиске и 2 чекбокса нажать, чтобы найти нужное. Если везде не поставлю required=False, с человека будет требовать заполнить все поля в форме, что, вероятно, приведет к слишком узкому поиску.

2021-05-28 09:43 UTC, intr00der commented on src/apps/apartments/forms.py
> +    def clean(self, *args, **kwargs):
Если я не подпишу *args, **kwargs, пишет, что self принял больше переменных, чем ему нужно было и ничего не работает. Вероятно, я подаю слишком много туда, но пока мне тяжело до конца понять.

2021-05-28 09:44 UTC, intr00der commented on src/apps/apartments/models.py
> +    class Rating(models.IntegerChoices):
Так обычно ведь звездочки нажимают (1-5), где нажали - такой и выбор

2021-05-28 09:49 UTC, intr00der commented on src/apps/apartments/views.py
> +            redirect('home')
Видеть список ждущих верификации объектов могут только суперюзеры, у них и в html кнопка "List of unverified apartments" не появляется. Я сделал это, чтобы человек, который не суперюзер, не мог вписать url и оказаться там. Я должен еще во вью списка апартаментов юзера добавить статус "на рассмотрении" или типа того.

2021-05-28 11:07 UTC, HackoDev requested changes

2021-05-28 11:07 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    def clean(self, *args, **kwargs):
просто посмотри на оригинальный вызов и всё и сделай так же

2021-05-28 11:07 UTC, HackoDev commented on src/apps/apartments/models.py
> +    class Rating(models.IntegerChoices):
ну и что, а зачем код усложнять чойсами, если достаточно проверить диапазон

2021-05-28 11:07 UTC, HackoDev commented on src/apps/apartments/views.py
> +            redirect('home')
я о другом- зачем тут бесполезная строка redirect

2021-06-02 09:54 UTC, HackoDev requested changes

2021-06-02 09:54 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    def save_apartment_with_added_data(self):
просто переопредели метод save и всё, зачем эти доп. методы

2021-06-02 09:54 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    def save_booking_with_added_data(self):
аналогично, есть метод save, зачем нужно что-то еще. переопредели

2021-06-02 09:54 UTC, HackoDev commented on src/apps/apartments/forms.py
> +        if crossed_bookings:
что произойдет, если ты напишешь такое условие (поведение на уровне ORM/SQL)?

2021-06-02 09:54 UTC, HackoDev commented on src/apps/apartments/forms.py
> +    def save_review_with_added_data(self):
save

2021-06-02 09:54 UTC, HackoDev commented on src/apps/apartments/models.py
> +    # def calculate_average_rating(self):
?

2021-06-02 09:54 UTC, HackoDev commented on src/apps/apartments/models.py
> +from statistics import mean
удаляй неиспользованные импорты

2021-06-02 09:54 UTC, HackoDev commented on src/apps/apartments/services.py
> +User = get_user_model()
если ты пишешь библиотеку, то я топлю за использование get_user_model, но если ты пишешь свой проект, в котором ты устанавливаешь правила, то хардкодим модель через импорт.

2021-06-02 09:54 UTC, HackoDev commented on src/apps/apartments/signals.py
> +    instance.apartment.average_rating = round(avg['rating__avg'], 2)
что происходит здесь, когда ты так вызываешь обновление поля?
найди другое решение

2021-06-02 09:54 UTC, HackoDev commented on src/chat/models.py
> +    timestamp = models.DateTimeField(auto_now_add=True)
у одних моделей- created_at,  а здесь timestamp. в чем разница? давай именовать одинаково везде, если совпадает цель.

2021-06-02 09:54 UTC, HackoDev commented on src/conf/asgi.py
> +os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings")
интересно, зачем?)

2021-06-02 09:54 UTC, HackoDev commented on src/conf/settings.py
> +# ASGI_APPLICATION = 'conf.asgi.application'
?

2021-06-02 09:54 UTC, HackoDev commented on src/conf/settings.py
> -STATIC_ROOT = os.path.join(BASE_DIR, 'static')
куда делся static root?

2021-06-02 13:04 UTC, intr00der commented on src/conf/asgi.py
> +os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings")
Вставлял с доков джанги чистый asgi.py, забыл сменить, extra cringe

2021-06-07 08:44 UTC, HackoDev requested changes

2021-06-07 08:44 UTC, HackoDev commented on src/static/js/bookingDatepicker.jquery.js
> +function DisableDates(date) {
по смыслу имя функции говорит немного другое, нежели её реализация. + camelCase.

2021-06-07 08:44 UTC, HackoDev commented on src/templates/apartments/apartment-form-profile.html
> +        $(document).ready( function() {
почему тут в html, а в других местах в js файлах?

2021-06-07 08:44 UTC, HackoDev commented on src/templates/apartments/book_apartment.html
> +    console.log(bookedDays)
console.log удаляем

2021-06-07 08:44 UTC, HackoDev commented on src/templates/apartments/home.html
> +            <a href="?page={{ apartments_page.paginator.num_pages }}">last &raquo;</a>
почему нельзя просто `page` назвать?

2021-06-07 08:44 UTC, HackoDev commented on src/templates/users/detail.html
> +{% block content %}
разделяй блоки пустой строкой

2021-06-09 09:14 UTC, merged